"""Expanded album lists - aiming for 1000+ quality albums."""

# Rate Your Music Top Albums (community-driven, quality focused)
RYM_TOP_ALBUMS = [
    # 2020s
    {"artist": "Black Country, New Road", "album": "Ants From Up There", "year": 2022},
    {"artist": "Beyoncé", "album": "Renaissance", "year": 2022},
    {"artist": "Alvvays", "album": "Blue Rev", "year": 2022},
    {"artist": "The Smile", "album": "A Light for Attracting Attention", "year": 2022},
    {"artist": "Weyes Blood", "album": "And in the Darkness, Hearts Aglow", "year": 2022},
    {"artist": "Rosalía", "album": "Motomami", "year": 2022},
    {"artist": "Björk", "album": "Fossora", "year": 2022},
    {"artist": "Fontaines D.C.", "album": "Skinty Fia", "year": 2022},
    {"artist": "Kendrick Lamar", "album": "Mr. Morale & The Big Steppers", "year": 2022},
    {"artist": "Denzel Curry", "album": "Melt My Eyez See Your Future", "year": 2022},
    {"artist": "Pusha T", "album": "It's Almost Dry", "year": 2022},
    {"artist": "Earl Sweatshirt", "album": "Sick!", "year": 2022},
    {"artist": "Charli XCX", "album": "Crash", "year": 2022},
    {"artist": "Beach House", "album": "Once Twice Melody", "year": 2022},
    {"artist": "Wet Leg", "album": "Wet Leg", "year": 2022},
    {"artist": "Arcade Fire", "album": "WE", "year": 2022},
    {"artist": "Father John Misty", "album": "Chloë and the Next 20th Century", "year": 2022},
    {"artist": "Spiritualized", "album": "Everything Was Beautiful", "year": 2022},
    {"artist": "King Gizzard & The Lizard Wizard", "album": "Omnium Gatherum", "year": 2022},
    {"artist": "Animal Collective", "album": "Time Skiffs", "year": 2022},
    # 2021
    {"artist": "Tyler, the Creator", "album": "Call Me If You Get Lost", "year": 2021},
    {"artist": "Japanese Breakfast", "album": "Jubilee", "year": 2021},
    {"artist": "Low", "album": "HEY WHAT", "year": 2021},
    {"artist": "Magdalena Bay", "album": "Mercurial World", "year": 2021},
    {"artist": "Silk Sonic", "album": "An Evening with Silk Sonic", "year": 2021},
    {"artist": "St. Vincent", "album": "Daddy's Home", "year": 2021},
    {"artist": "Halsey", "album": "If I Can't Have Love, I Want Power", "year": 2021},
    {"artist": "Lorde", "album": "Solar Power", "year": 2021},
    {"artist": "Billie Eilish", "album": "Happier Than Ever", "year": 2021},
    {"artist": "Clairo", "album": "Sling", "year": 2021},
    {"artist": "Wolf Alice", "album": "Blue Weekend", "year": 2021},
    {"artist": "Sufjan Stevens & Angelo De Augustine", "album": "A Beginner's Mind", "year": 2021},
    {"artist": "Nick Cave & Warren Ellis", "album": "Carnage", "year": 2021},
    {"artist": "Godspeed You! Black Emperor", "album": "G_d's Pee AT STATE'S END!", "year": 2021},
    {"artist": "Deafheaven", "album": "Infinite Granite", "year": 2021},
    {"artist": "Gojira", "album": "Fortitude", "year": 2021},
    {"artist": "Mastodon", "album": "Hushed and Grim", "year": 2021},
    {"artist": "Converge & Chelsea Wolfe", "album": "Bloodmoon: I", "year": 2021},
    {"artist": "Tropical Fuck Storm", "album": "Deep States", "year": 2021},
    {"artist": "Squid", "album": "Bright Green Field", "year": 2021},
]

# 2020
RYM_2020 = [
    {"artist": "Fiona Apple", "album": "Fetch the Bolt Cutters", "year": 2020},
    {"artist": "Run the Jewels", "album": "RTJ4", "year": 2020},
    {"artist": "Phoebe Bridgers", "album": "Punisher", "year": 2020},
    {"artist": "Mac Miller", "album": "Circles", "year": 2020},
    {"artist": "Perfume Genius", "album": "Set My Heart on Fire Immediately", "year": 2020},
    {"artist": "Charli XCX", "album": "how i'm feeling now", "year": 2020},
    {"artist": "Dua Lipa", "album": "Future Nostalgia", "year": 2020},
    {"artist": "The Strokes", "album": "The New Abnormal", "year": 2020},
    {"artist": "Yves Tumor", "album": "Heaven to a Tortured Mind", "year": 2020},
    {"artist": "Moses Sumney", "album": "græ", "year": 2020},
    {"artist": "Waxahatchee", "album": "Saint Cloud", "year": 2020},
    {"artist": "Fleet Foxes", "album": "Shore", "year": 2020},
    {"artist": "Sufjan Stevens", "album": "The Ascension", "year": 2020},
    {"artist": "Tame Impala", "album": "The Slow Rush", "year": 2020},
    {"artist": "Grimes", "album": "Miss Anthropocene", "year": 2020},
    {"artist": "Caribou", "album": "Suddenly", "year": 2020},
    {"artist": "Kelly Lee Owens", "album": "Inner Song", "year": 2020},
    {"artist": "Jessie Ware", "album": "What's Your Pleasure?", "year": 2020},
    {"artist": "Róisín Murphy", "album": "Róisín Machine", "year": 2020},
    {"artist": "Thundercat", "album": "It Is What It Is", "year": 2020},
]

# 2019
RYM_2019 = [
    {"artist": "Tyler, the Creator", "album": "IGOR", "year": 2019},
    {"artist": "Weyes Blood", "album": "Titanic Rising", "year": 2019},
    {"artist": "FKA twigs", "album": "Magdalene", "year": 2019},
    {"artist": "Angel Olsen", "album": "All Mirrors", "year": 2019},
    {"artist": "Nick Cave & The Bad Seeds", "album": "Ghosteen", "year": 2019},
    {"artist": "Lana Del Rey", "album": "Norman Fucking Rockwell!", "year": 2019},
    {"artist": "Billie Eilish", "album": "When We All Fall Asleep, Where Do We Go?", "year": 2019},
    {"artist": "Solange", "album": "When I Get Home", "year": 2019},
    {"artist": "Sharon Van Etten", "album": "Remind Me Tomorrow", "year": 2019},
    {"artist": "Big Thief", "album": "Two Hands", "year": 2019},
    {"artist": "Brittany Howard", "album": "Jaime", "year": 2019},
    {"artist": "Purple Mountains", "album": "Purple Mountains", "year": 2019},
    {"artist": "Thom Yorke", "album": "Anima", "year": 2019},
    {"artist": "Bon Iver", "album": "i,i", "year": 2019},
    {"artist": "Vampire Weekend", "album": "Father of the Bride", "year": 2019},
    {"artist": "The National", "album": "I Am Easy to Find", "year": 2019},
    {"artist": "Fontaines D.C.", "album": "Dogrel", "year": 2019},
    {"artist": "black midi", "album": "Schlagenheim", "year": 2019},
    {"artist": "King Gizzard & The Lizard Wizard", "album": "Infest the Rats' Nest", "year": 2019},
    {"artist": "Tool", "album": "Fear Inoculum", "year": 2019},
]

# 2018
RYM_2018 = [
    {"artist": "Daughters", "album": "You Won't Get What You Want", "year": 2018},
    {"artist": "Kids See Ghosts", "album": "Kids See Ghosts", "year": 2018},
    {"artist": "Pusha T", "album": "Daytona", "year": 2018},
    {"artist": "Earl Sweatshirt", "album": "Some Rap Songs", "year": 2018},
    {"artist": "Kali Uchis", "album": "Isolation", "year": 2018},
    {"artist": "Janelle Monáe", "album": "Dirty Computer", "year": 2018},
    {"artist": "Robyn", "album": "Honey", "year": 2018},
    {"artist": "Beach House", "album": "7", "year": 2018},
    {"artist": "Deafheaven", "album": "Ordinary Corrupt Human Love", "year": 2018},
    {"artist": "Sleep", "album": "The Sciences", "year": 2018},
    {"artist": "Yob", "album": "Our Raw Heart", "year": 2018},
    {"artist": "Zeal & Ardor", "album": "Stranger Fruit", "year": 2018},
    {"artist": "Low", "album": "Double Negative", "year": 2018},
    {"artist": "Grouper", "album": "Grid of Points", "year": 2018},
    {"artist": "Oneohtrix Point Never", "album": "Age Of", "year": 2018},
    {"artist": "Jon Hopkins", "album": "Singularity", "year": 2018},
    {"artist": "Aphex Twin", "album": "Collapse EP", "year": 2018},
    {"artist": "Kamasi Washington", "album": "Heaven and Earth", "year": 2018},
    {"artist": "Nils Frahm", "album": "All Melody", "year": 2018},
    {"artist": "Anna von Hausswolff", "album": "Dead Magic", "year": 2018},
]

# 2017
RYM_2017 = [
    {"artist": "Kendrick Lamar", "album": "DAMN.", "year": 2017},
    {"artist": "Lorde", "album": "Melodrama", "year": 2017},
    {"artist": "SZA", "album": "Ctrl", "year": 2017},
    {"artist": "Brockhampton", "album": "Saturation III", "year": 2017},
    {"artist": "Fleet Foxes", "album": "Crack-Up", "year": 2017},
    {"artist": "Father John Misty", "album": "Pure Comedy", "year": 2017},
    {"artist": "Mount Eerie", "album": "A Crow Looked at Me", "year": 2017},
    {"artist": "The War on Drugs", "album": "A Deeper Understanding", "year": 2017},
    {"artist": "LCD Soundsystem", "album": "American Dream", "year": 2017},
    {"artist": "St. Vincent", "album": "Masseduction", "year": 2017},
    {"artist": "Björk", "album": "Utopia", "year": 2017},
    {"artist": "King Krule", "album": "The Ooz", "year": 2017},
    {"artist": "Slowdive", "album": "Slowdive", "year": 2017},
    {"artist": "Ride", "album": "Weather Diaries", "year": 2017},
    {"artist": "The National", "album": "Sleep Well Beast", "year": 2017},
    {"artist": "Arcade Fire", "album": "Everything Now", "year": 2017},
    {"artist": "Queens of the Stone Age", "album": "Villains", "year": 2017},
    {"artist": "Converge", "album": "The Dusk in Us", "year": 2017},
    {"artist": "Power Trip", "album": "Nightmare Logic", "year": 2017},
    {"artist": "Pallbearer", "album": "Heartless", "year": 2017},
]

# 2016
RYM_2016 = [
    {"artist": "David Bowie", "album": "Blackstar", "year": 2016},
    {"artist": "Beyoncé", "album": "Lemonade", "year": 2016},
    {"artist": "Frank Ocean", "album": "Blonde", "year": 2016},
    {"artist": "Radiohead", "album": "A Moon Shaped Pool", "year": 2016},
    {"artist": "Kanye West", "album": "The Life of Pablo", "year": 2016},
    {"artist": "Chance the Rapper", "album": "Coloring Book", "year": 2016},
    {"artist": "A Tribe Called Quest", "album": "We Got It from Here... Thank You 4 Your Service", "year": 2016},
    {"artist": "Anderson .Paak", "album": "Malibu", "year": 2016},
    {"artist": "Solange", "album": "A Seat at the Table", "year": 2016},
    {"artist": "Blood Orange", "album": "Freetown Sound", "year": 2016},
    {"artist": "Nick Cave & The Bad Seeds", "album": "Skeleton Tree", "year": 2016},
    {"artist": "Leonard Cohen", "album": "You Want It Darker", "year": 2016},
    {"artist": "Angel Olsen", "album": "My Woman", "year": 2016},
    {"artist": "Car Seat Headrest", "album": "Teens of Denial", "year": 2016},
    {"artist": "Bon Iver", "album": "22, A Million", "year": 2016},
    {"artist": "The Avalanches", "album": "Wildflower", "year": 2016},
    {"artist": "Swans", "album": "The Glowing Man", "year": 2016},
    {"artist": "Meshuggah", "album": "The Violent Sleep of Reason", "year": 2016},
    {"artist": "Vektor", "album": "Terminal Redux", "year": 2016},
    {"artist": "Oranssi Pazuzu", "album": "Värähtelijä", "year": 2016},
]

# 2015
RYM_2015 = [
    {"artist": "Kendrick Lamar", "album": "To Pimp a Butterfly", "year": 2015},
    {"artist": "Sufjan Stevens", "album": "Carrie & Lowell", "year": 2015},
    {"artist": "Tame Impala", "album": "Currents", "year": 2015},
    {"artist": "Grimes", "album": "Art Angels", "year": 2015},
    {"artist": "Father John Misty", "album": "I Love You, Honeybear", "year": 2015},
    {"artist": "Björk", "album": "Vulnicura", "year": 2015},
    {"artist": "Joanna Newsom", "album": "Divers", "year": 2015},
    {"artist": "Beach House", "album": "Depression Cherry", "year": 2015},
    {"artist": "Courtney Barnett", "album": "Sometimes I Sit and Think, and Sometimes I Just Sit", "year": 2015},
    {"artist": "Vince Staples", "album": "Summertime '06", "year": 2015},
    {"artist": "Jamie xx", "album": "In Colour", "year": 2015},
    {"artist": "Floating Points", "album": "Elaenia", "year": 2015},
    {"artist": "Oneohtrix Point Never", "album": "Garden of Delete", "year": 2015},
    {"artist": "Deafheaven", "album": "New Bermuda", "year": 2015},
    {"artist": "Ghost", "album": "Meliora", "year": 2015},
    {"artist": "Tribulation", "album": "The Children of the Night", "year": 2015},
    {"artist": "Mgła", "album": "Exercises in Futility", "year": 2015},
    {"artist": "Leviathan", "album": "Scar Sighted", "year": 2015},
    {"artist": "Steven Wilson", "album": "Hand. Cannot. Erase.", "year": 2015},
    {"artist": "Godspeed You! Black Emperor", "album": "Asunder, Sweet and Other Distress", "year": 2015},
]

# 2014
RYM_2014 = [
    {"artist": "D'Angelo", "album": "Black Messiah", "year": 2014},
    {"artist": "Run the Jewels", "album": "Run the Jewels 2", "year": 2014},
    {"artist": "St. Vincent", "album": "St. Vincent", "year": 2014},
    {"artist": "Flying Lotus", "album": "You're Dead!", "year": 2014},
    {"artist": "Aphex Twin", "album": "Syro", "year": 2014},
    {"artist": "The War on Drugs", "album": "Lost in the Dream", "year": 2014},
    {"artist": "Mac DeMarco", "album": "Salad Days", "year": 2014},
    {"artist": "Ariel Pink", "album": "pom pom", "year": 2014},
    {"artist": "Todd Terje", "album": "It's Album Time", "year": 2014},
    {"artist": "Caribou", "album": "Our Love", "year": 2014},
    {"artist": "Arca", "album": "Xen", "year": 2014},
    {"artist": "Swans", "album": "To Be Kind", "year": 2014},
    {"artist": "Sun Kil Moon", "album": "Benji", "year": 2014},
    {"artist": "Sharon Van Etten", "album": "Are We There", "year": 2014},
    {"artist": "Angel Olsen", "album": "Burn Your Fire for No Witness", "year": 2014},
    {"artist": "Pallbearer", "album": "Foundations of Burden", "year": 2014},
    {"artist": "Mastodon", "album": "Once More 'Round the Sun", "year": 2014},
    {"artist": "Behemoth", "album": "The Satanist", "year": 2014},
    {"artist": "Agalloch", "album": "The Serpent & the Sphere", "year": 2014},
    {"artist": "Thou", "album": "Heathen", "year": 2014},
]

# 2013
RYM_2013 = [
    {"artist": "Kanye West", "album": "Yeezus", "year": 2013},
    {"artist": "Vampire Weekend", "album": "Modern Vampires of the City", "year": 2013},
    {"artist": "Arcade Fire", "album": "Reflektor", "year": 2013},
    {"artist": "My Bloody Valentine", "album": "m b v", "year": 2013},
    {"artist": "Daft Punk", "album": "Random Access Memories", "year": 2013},
    {"artist": "Queens of the Stone Age", "album": "...Like Clockwork", "year": 2013},
    {"artist": "The National", "album": "Trouble Will Find Me", "year": 2013},
    {"artist": "Boards of Canada", "album": "Tomorrow's Harvest", "year": 2013},
    {"artist": "Deafheaven", "album": "Sunbather", "year": 2013},
    {"artist": "Gorguts", "album": "Colored Sands", "year": 2013},
    {"artist": "Carcass", "album": "Surgical Steel", "year": 2013},
    {"artist": "Cult of Luna & Julie Christmas", "album": "Mariner", "year": 2013},
    {"artist": "Disclosure", "album": "Settle", "year": 2013},
    {"artist": "Jon Hopkins", "album": "Immunity", "year": 2013},
    {"artist": "Tim Hecker", "album": "Virgins", "year": 2013},
    {"artist": "Oneohtrix Point Never", "album": "R Plus Seven", "year": 2013},
    {"artist": "Bill Callahan", "album": "Dream River", "year": 2013},
    {"artist": "Kurt Vile", "album": "Wakin on a Pretty Daze", "year": 2013},
    {"artist": "Savages", "album": "Silence Yourself", "year": 2013},
    {"artist": "Haim", "album": "Days Are Gone", "year": 2013},
]

# 2010-2012
RYM_2010_2012 = [
    {"artist": "Kendrick Lamar", "album": "good kid, m.A.A.d city", "year": 2012},
    {"artist": "Frank Ocean", "album": "Channel Orange", "year": 2012},
    {"artist": "Fiona Apple", "album": "The Idler Wheel...", "year": 2012},
    {"artist": "Grimes", "album": "Visions", "year": 2012},
    {"artist": "Beach House", "album": "Bloom", "year": 2012},
    {"artist": "Tame Impala", "album": "Lonerism", "year": 2012},
    {"artist": "Swans", "album": "The Seer", "year": 2012},
    {"artist": "Death Grips", "album": "The Money Store", "year": 2012},
    {"artist": "Killer Mike", "album": "R.A.P. Music", "year": 2012},
    {"artist": "Pallbearer", "album": "Sorrow and Extinction", "year": 2012},
    {"artist": "Bon Iver", "album": "Bon Iver", "year": 2011},
    {"artist": "Fleet Foxes", "album": "Helplessness Blues", "year": 2011},
    {"artist": "Radiohead", "album": "The King of Limbs", "year": 2011},
    {"artist": "James Blake", "album": "James Blake", "year": 2011},
    {"artist": "St. Vincent", "album": "Strange Mercy", "year": 2011},
    {"artist": "M83", "album": "Hurry Up, We're Dreaming", "year": 2011},
    {"artist": "Mastodon", "album": "The Hunter", "year": 2011},
    {"artist": "Opeth", "album": "Heritage", "year": 2011},
    {"artist": "Kanye West", "album": "My Beautiful Dark Twisted Fantasy", "year": 2010},
    {"artist": "Arcade Fire", "album": "The Suburbs", "year": 2010},
    {"artist": "Beach House", "album": "Teen Dream", "year": 2010},
    {"artist": "LCD Soundsystem", "album": "This Is Happening", "year": 2010},
    {"artist": "Deerhunter", "album": "Halcyon Digest", "year": 2010},
    {"artist": "The National", "album": "High Violet", "year": 2010},
    {"artist": "Sufjan Stevens", "album": "The Age of Adz", "year": 2010},
    {"artist": "Joanna Newsom", "album": "Have One on Me", "year": 2010},
    {"artist": "Flying Lotus", "album": "Cosmogramma", "year": 2010},
    {"artist": "Gorillaz", "album": "Plastic Beach", "year": 2010},
    {"artist": "Big Boi", "album": "Sir Lucious Left Foot", "year": 2010},
    {"artist": "Janelle Monáe", "album": "The ArchAndroid", "year": 2010},
]

# 2000s essentials
RYM_2000S = [
    {"artist": "Radiohead", "album": "Kid A", "year": 2000},
    {"artist": "Radiohead", "album": "Amnesiac", "year": 2001},
    {"artist": "Radiohead", "album": "In Rainbows", "year": 2007},
    {"artist": "The Strokes", "album": "Is This It", "year": 2001},
    {"artist": "The White Stripes", "album": "White Blood Cells", "year": 2001},
    {"artist": "Interpol", "album": "Turn On the Bright Lights", "year": 2002},
    {"artist": "Wilco", "album": "Yankee Hotel Foxtrot", "year": 2002},
    {"artist": "The Flaming Lips", "album": "Yoshimi Battles the Pink Robots", "year": 2002},
    {"artist": "Sigur Rós", "album": "( )", "year": 2002},
    {"artist": "OutKast", "album": "Speakerboxxx/The Love Below", "year": 2003},
    {"artist": "The Postal Service", "album": "Give Up", "year": 2003},
    {"artist": "Arcade Fire", "album": "Funeral", "year": 2004},
    {"artist": "Madvillain", "album": "Madvillainy", "year": 2004},
    {"artist": "Modest Mouse", "album": "Good News for People Who Love Bad News", "year": 2004},
    {"artist": "Sufjan Stevens", "album": "Illinois", "year": 2005},
    {"artist": "LCD Soundsystem", "album": "Sound of Silver", "year": 2007},
    {"artist": "Panda Bear", "album": "Person Pitch", "year": 2007},
    {"artist": "Animal Collective", "album": "Merriweather Post Pavilion", "year": 2009},
    {"artist": "Grizzly Bear", "album": "Veckatimest", "year": 2009},
    {"artist": "The xx", "album": "xx", "year": 2009},
]

# 90s essentials
RYM_90S = [
    {"artist": "Radiohead", "album": "OK Computer", "year": 1997},
    {"artist": "Radiohead", "album": "The Bends", "year": 1995},
    {"artist": "Nirvana", "album": "Nevermind", "year": 1991},
    {"artist": "Nirvana", "album": "In Utero", "year": 1993},
    {"artist": "My Bloody Valentine", "album": "Loveless", "year": 1991},
    {"artist": "Massive Attack", "album": "Blue Lines", "year": 1991},
    {"artist": "Portishead", "album": "Dummy", "year": 1994},
    {"artist": "Björk", "album": "Homogenic", "year": 1997},
    {"artist": "Björk", "album": "Post", "year": 1995},
    {"artist": "PJ Harvey", "album": "Rid of Me", "year": 1993},
    {"artist": "Jeff Buckley", "album": "Grace", "year": 1994},
    {"artist": "Elliott Smith", "album": "Either/Or", "year": 1997},
    {"artist": "Neutral Milk Hotel", "album": "In the Aeroplane Over the Sea", "year": 1998},
    {"artist": "Godspeed You! Black Emperor", "album": "F♯ A♯ ∞", "year": 1997},
    {"artist": "Mogwai", "album": "Young Team", "year": 1997},
    {"artist": "Slint", "album": "Spiderland", "year": 1991},
    {"artist": "Talk Talk", "album": "Laughing Stock", "year": 1991},
    {"artist": "Spiritualized", "album": "Ladies and Gentlemen We Are Floating in Space", "year": 1997},
    {"artist": "The Verve", "album": "Urban Hymns", "year": 1997},
    {"artist": "Oasis", "album": "(What's the Story) Morning Glory?", "year": 1995},
    {"artist": "Blur", "album": "Parklife", "year": 1994},
    {"artist": "Pulp", "album": "Different Class", "year": 1995},
    {"artist": "Belle and Sebastian", "album": "If You're Feeling Sinister", "year": 1996},
    {"artist": "Pavement", "album": "Crooked Rain, Crooked Rain", "year": 1994},
    {"artist": "Weezer", "album": "Pinkerton", "year": 1996},
    {"artist": "Smashing Pumpkins", "album": "Siamese Dream", "year": 1993},
    {"artist": "Smashing Pumpkins", "album": "Mellon Collie and the Infinite Sadness", "year": 1995},
    {"artist": "Nine Inch Nails", "album": "The Downward Spiral", "year": 1994},
    {"artist": "Tool", "album": "Ænima", "year": 1996},
    {"artist": "Alice in Chains", "album": "Dirt", "year": 1992},
]

# 80s essentials
RYM_80S = [
    {"artist": "Talking Heads", "album": "Remain in Light", "year": 1980},
    {"artist": "Joy Division", "album": "Closer", "year": 1980},
    {"artist": "The Smiths", "album": "The Queen Is Dead", "year": 1986},
    {"artist": "Kate Bush", "album": "Hounds of Love", "year": 1985},
    {"artist": "Pixies", "album": "Doolittle", "year": 1989},
    {"artist": "Pixies", "album": "Surfer Rosa", "year": 1988},
    {"artist": "Sonic Youth", "album": "Daydream Nation", "year": 1988},
    {"artist": "My Bloody Valentine", "album": "Isn't Anything", "year": 1988},
    {"artist": "Cocteau Twins", "album": "Heaven or Las Vegas", "year": 1990},
    {"artist": "The Cure", "album": "Disintegration", "year": 1989},
    {"artist": "Depeche Mode", "album": "Violator", "year": 1990},
    {"artist": "New Order", "album": "Power, Corruption & Lies", "year": 1983},
    {"artist": "Prince", "album": "Purple Rain", "year": 1984},
    {"artist": "Prince", "album": "Sign o' the Times", "year": 1987},
    {"artist": "Michael Jackson", "album": "Thriller", "year": 1982},
    {"artist": "Public Enemy", "album": "It Takes a Nation of Millions to Hold Us Back", "year": 1988},
    {"artist": "N.W.A", "album": "Straight Outta Compton", "year": 1988},
    {"artist": "Beastie Boys", "album": "Paul's Boutique", "year": 1989},
    {"artist": "Slayer", "album": "Reign in Blood", "year": 1986},
    {"artist": "Metallica", "album": "Master of Puppets", "year": 1986},
]

# 70s essentials
RYM_70S = [
    {"artist": "David Bowie", "album": "The Rise and Fall of Ziggy Stardust", "year": 1972},
    {"artist": "David Bowie", "album": "Low", "year": 1977},
    {"artist": "David Bowie", "album": "Heroes", "year": 1977},
    {"artist": "Pink Floyd", "album": "The Dark Side of the Moon", "year": 1973},
    {"artist": "Pink Floyd", "album": "Wish You Were Here", "year": 1975},
    {"artist": "Led Zeppelin", "album": "Led Zeppelin IV", "year": 1971},
    {"artist": "Led Zeppelin", "album": "Physical Graffiti", "year": 1975},
    {"artist": "Black Sabbath", "album": "Paranoid", "year": 1970},
    {"artist": "Black Sabbath", "album": "Master of Reality", "year": 1971},
    {"artist": "King Crimson", "album": "In the Court of the Crimson King", "year": 1969},
    {"artist": "King Crimson", "album": "Red", "year": 1974},
    {"artist": "Yes", "album": "Close to the Edge", "year": 1972},
    {"artist": "Genesis", "album": "Selling England by the Pound", "year": 1973},
    {"artist": "Stevie Wonder", "album": "Songs in the Key of Life", "year": 1976},
    {"artist": "Stevie Wonder", "album": "Innervisions", "year": 1973},
    {"artist": "Marvin Gaye", "album": "What's Going On", "year": 1971},
    {"artist": "Curtis Mayfield", "album": "Superfly", "year": 1972},
    {"artist": "Sly & The Family Stone", "album": "There's a Riot Goin' On", "year": 1971},
    {"artist": "Parliament", "album": "Mothership Connection", "year": 1975},
    {"artist": "Funkadelic", "album": "Maggot Brain", "year": 1971},
    {"artist": "Fleetwood Mac", "album": "Rumours", "year": 1977},
    {"artist": "Joni Mitchell", "album": "Blue", "year": 1971},
    {"artist": "Neil Young", "album": "After the Gold Rush", "year": 1970},
    {"artist": "Bob Dylan", "album": "Blood on the Tracks", "year": 1975},
    {"artist": "The Clash", "album": "London Calling", "year": 1979},
    {"artist": "Sex Pistols", "album": "Never Mind the Bollocks", "year": 1977},
    {"artist": "Ramones", "album": "Ramones", "year": 1976},
    {"artist": "Television", "album": "Marquee Moon", "year": 1977},
    {"artist": "Wire", "album": "Pink Flag", "year": 1977},
    {"artist": "Kraftwerk", "album": "Trans-Europe Express", "year": 1977},
]

# 60s essentials
RYM_60S = [
    {"artist": "The Beatles", "album": "Abbey Road", "year": 1969},
    {"artist": "The Beatles", "album": "Sgt. Pepper's Lonely Hearts Club Band", "year": 1967},
    {"artist": "The Beatles", "album": "Revolver", "year": 1966},
    {"artist": "The Beatles", "album": "The White Album", "year": 1968},
    {"artist": "The Velvet Underground", "album": "The Velvet Underground & Nico", "year": 1967},
    {"artist": "The Beach Boys", "album": "Pet Sounds", "year": 1966},
    {"artist": "Bob Dylan", "album": "Highway 61 Revisited", "year": 1965},
    {"artist": "Bob Dylan", "album": "Blonde on Blonde", "year": 1966},
    {"artist": "The Jimi Hendrix Experience", "album": "Are You Experienced", "year": 1967},
    {"artist": "The Jimi Hendrix Experience", "album": "Electric Ladyland", "year": 1968},
    {"artist": "The Doors", "album": "The Doors", "year": 1967},
    {"artist": "Van Morrison", "album": "Astral Weeks", "year": 1968},
    {"artist": "The Who", "album": "Tommy", "year": 1969},
    {"artist": "The Rolling Stones", "album": "Let It Bleed", "year": 1969},
    {"artist": "Simon & Garfunkel", "album": "Bridge over Troubled Water", "year": 1970},
    {"artist": "John Coltrane", "album": "A Love Supreme", "year": 1965},
    {"artist": "Miles Davis", "album": "Kind of Blue", "year": 1959},
    {"artist": "Miles Davis", "album": "Bitches Brew", "year": 1970},
    {"artist": "Nina Simone", "album": "I Put a Spell on You", "year": 1965},
    {"artist": "Aretha Franklin", "album": "I Never Loved a Man the Way I Love You", "year": 1967},
]


# Combine all lists
ALL_RYM_ALBUMS = (
    RYM_TOP_ALBUMS + RYM_2020 + RYM_2019 + RYM_2018 + RYM_2017 + 
    RYM_2016 + RYM_2015 + RYM_2014 + RYM_2013 + RYM_2010_2012 +
    RYM_2000S + RYM_90S + RYM_80S + RYM_70S + RYM_60S
)


def fetch_rym_top_albums() -> list[dict]:
    """Return Rate Your Music top albums across all decades."""
    print("Fetching RYM Top Albums...")
    albums = []
    for item in ALL_RYM_ALBUMS:
        albums.append({
            "artist": item["artist"],
            "title": item["album"],
            "year": item["year"],
            "recognitions": [{"type": "RYM Essential", "year": item["year"], "details": "Community Pick"}],
        })
    print(f"  Found {len(albums)} albums")
    return albums
